### ISSUE TITLE
Player App has a blank screen  only Header and footer is displayed

### ISSUE THREAD

**Issue by borkya** [developerforce/quiz-host-app#99]
Cannot register a player . Player App has a blank screen  only Header and footer is displayed

**Comment by pozil** [comment]
Can you share more information?
I need the following:
- player and host app versions
- browser experiencing the issue

Also, can you try to open the player app on a desktop browser and check the output of the browser's developer console?

**Comment by borkya** [comment]
Player App version :  Player app v1.0.0 
Host App : Host app v2.9.0
Google Chrome , I'm using it on Desktop , mobile also has same experience on Chrome. 

Dev Console log  - 
WS opening  wss://ssb-quiz-app.herokuapp.com
app.js:1          GET https://ssb-quiz-app.herokuapp.com/api/quiz-sessions 500 (Internal Server Error)
app.js:1 WS open

**Comment by pozil** [comment]
I see that you have an error on the Heroku side, could you restart your dyno, look at the Heroku logs while try to register again with the mobile app.
Before doing this, make sure to update your player app as latest version is 3.0.1.

**Comment by pozil** [comment]
Any update on your end?

**Comment by borkya** [comment]
Im closing this issue now, I will reopen or create a new one when I'm able to spend time to troubleshoot this. Thanks for your help Phiippe.
